general.import = ["~/.config/alacritty/themes/tokyonight.toml"]

[font]
size = 16.0

[font.normal]
family = "Maple Mono NF Thin"
style = "Regular"

[font.bold]
family = "Maple Mono NF Thin"
style = "Bold"

[font.italic]
family = "Maple Mono NF Thin"
style = "Italic"

[font.bold_italic]
family = "Maple Mono NF Thin"
style = "Bold Italic"

# [font.normal]
# family = "Iosevka Nerd Font Propo"
# style = "Regular"
# 
# [font.bold]
# family = "Iosevka Nerd Font Propo"
# style = "Bold"
# 
# [font.italic]
# family = "Iosevka Nerd Font Propo"
# style = "Italic"
# 
# [font.bold_italic]
# family = "Iosevka Nerd Font Propo"
# style = "Bold Italic"

[window]
startup_mode = "Maximized"
opacity = 0.95
blur = false

[cursor]
blink_timeout = 0 
style = { shape = "Underline", blinking = "On"  }
thickness = 0.4
blink_interval = 400

[colors.cursor]
text = "CellForeground"  # Texte du curseur (par défaut: couleur de la cellule)
cursor = "#bb9af7"  
