shell = "zsh"

[templates] 
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
fpath = 'fpath=( "{{ dir }}" $fpath )'

[plugins]
# colorisation des commandes (ne supporte pas 'defer')
[plugins.grc]
local = "~/.config/sheldon/grc"
use = ["*"]

# pour déférer les plugins et accélérer le chargement initial
[plugins.zsh-defer] 
github = "romkatv/zsh-defer"

# mise en cache des plugins compatibles
[plugins.evalcache]
github = "mroth/evalcache"

# ajout de commandes d'auto-completions
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["fpath"]
dir = "src"

# fzf-tab affiche l'autocompletion avec fzf
[plugins.fzf-tab] 
github = "Aloxaf/fzf-tab"
apply = ["defer"]

# suggestions automatiques grises au bout de la commande prétapée
[plugins.zsh-autosuggestions] 
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

# double ECHAP rappelle dernière commande et ajoute sudo devant
[plugins.sudo] 
github = "zap-zsh/sudo"
apply = ["defer"]

# remplace cd
[plugins.zsh-zoxide] 
github = "z-shell/zsh-zoxide"
apply = ["defer"]

# chargement alias & function perso
[plugins.aliases]
local = "~/.config/sheldon/olivier"
use = ["*"]
apply = ["defer"]

# pour pages de man en couleur
[plugins.batman] 
inline = 'zsh-defer _evalcache batman --export-env'

# prompt
[plugins.oh-my-posh] 
inline = 'zsh-defer _evalcache oh-my-posh init zsh --config $HOME/.config/ohmyposh/config.json'
